#!/bin/bash

## #ddev-generated
## Description: Install dependencies and run Drupal Canvas' UI app development server.
## Example: ddev xb-ui-dev
## Aliases: ui-dev,dev

cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/canvas" || exit 1

drush pm:install canvas_vite -y > /dev/null 2>&1 || :
npm ci
cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/canvas/ui" || exit 1
npm run drupaldev -- --host
